
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 25 21:14:37 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int LBRACKET = 43;
  public static final int INCREMENT = 35;
  public static final int CONST = 6;
  public static final int NUMCONST = 49;
  public static final int IFNOTEQUAL = 27;
  public static final int LPAREN = 41;
  public static final int GREATER = 28;
  public static final int CONTINUE = 15;
  public static final int DECREMENT = 36;
  public static final int LESS = 30;
  public static final int MINUS = 21;
  public static final int RPAREN = 42;
  public static final int SEMICOLON = 37;
  public static final int AND = 32;
  public static final int RECORD = 19;
  public static final int LESSEQUAL = 31;
  public static final int OR = 33;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int PLUS = 20;
  public static final int MULTIPLY = 22;
  public static final int IF = 51;
  public static final int ASSIGN = 34;
  public static final int THIS = 16;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 44;
  public static final int SUPER = 17;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int SQUARE = 25;
  public static final int MODULO = 24;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 29;
  public static final int COLON = 38;
  public static final int ELSE = 52;
  public static final int LBRACE = 45;
  public static final int ENUM = 5;
  public static final int READ = 11;
  public static final int GOTO = 18;
  public static final int CHARCONST = 48;
  public static final int WHILE = 8;
  public static final int RBRACE = 46;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int IFEQUAL = 26;
  public static final int PRINT = 10;
  public static final int DO = 7;
}

